### ISSUE TITLE
Restaurant Page: Github actions to deploy out dist folder

### ISSUE THREAD

**Issue by AnEvilPenguin** [TheOdinProject/curriculum#27614]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The Restaurant project page talks about using scripts to deploy out the dist folder using github pages.
An alternative would be to use GitHub actions to deploy out the page.
You can use the default static HTML template, and just modify the archive step to look at the dist folder instead of the whole repo.

![image](https://github.com/TheOdinProject/curriculum/assets/17614766/c9da0500-a76c-481a-857a-74e274e890dd)

```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Change this line from the default '.' to use './dist'
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

Feels like a simpler option than configuring and running a script every time you want to publish something new? I can see the actions thing being a can of worms if you don't want to introduce that sort of topic yet though!

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-restaurant-page

### (Optional) Additional Comments

If you wanted me working on this it would be my first contribution, so I might need a little bit of hand holding.
